import {StyleSheet} from 'react-native';
import colors from '../../styles/colors';

export default StyleSheet.create({
    bottomText:{
        fontSize:15,
        textAlign:'center',
        marginTop:22,
        marginBottom:30,
        marginLeft:7,
        color:colors.textGrey
    },
    main2:{
        flexDirection:'row'
    },
    img:{
        width:30,
        height:30,
        marginTop:20,
        marginLeft:20
    },
    main:{
        marginTop:-110,
        marginLeft:30
    },
    txt1:{
        fontSize:35,
        marginTop:3
    },
    txt2:{
        color:colors.textGreyB,
        marginTop:3
    },
    anotherText:{
        flexDirection:'row'
    },
    detail:{
        marginTop:15,
        marginLeft:160,
        borderWidth:1,
        width:90,
        textAlign:'center',
        borderColor:colors.textBlue,
        borderRadius:5,
        padding:4
    },
    txt3:{
        color:colors.white,
        marginLeft:70,
        marginTop:-60,
        fontSize:17
    },
    txt4:{
        color:colors.white,
        marginLeft:70,
        marginTop:7,
    },
    txt5:{
        color:colors.white,
        marginLeft:70,
    },
    img2:{
        width:40,
        height:40,
        marginTop:30,
        marginLeft:15,
    },
    anotherImg:{
        flexDirection:'row',
    },
    img3:{
        width:20,
        height:20,
        marginTop:7,
        marginLeft:60
    },
    header:{
        marginTop:-150,
        marginLeft:30
    },
    payment:{
        marginTop:60
    }
});
